<?xml version="1.0"?>

<!--

Gazebo Multirotor Definition File
Author: James Jackson

-->

<robot name="propeller_ccw" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Properties -->
  <xacro:property name="namespace" value="propeller_ccw" />
  <xacro:property name="color" value="White" />
  <xacro:property name="mass" value="1" />
  <xacro:property name="body_width" value="0.46" />
  <xacro:property name="body_height" value="0.16" />
  <xacro:property name="body_inertia">
    <inertia ixx="1" ixy="0.0" ixz="0.0" iyy="1" iyz="0.0" izz="1" />
  </xacro:property>
  <xacro:property name="use_mesh_file" value="true" />
  <xacro:property name="mesh_file" value="package://magicc_sim/meshes/propeller_ccw.dae" />

  <!-- *********************** GAZEBO ROBOT DEFINITION ******************* -->

  <link name="${namespace}/base_link">
    <inertial>
      <mass value="${mass}" />  <!-- [kg] -->
      <origin xyz="0 0 0" />
      <xacro:insert_block name="body_inertia" />
    </inertial>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <xacro:if value="${use_mesh_file}">
          <mesh filename="${mesh_file}" scale="1 1 1" />
        </xacro:if>
        <xacro:unless value="${use_mesh_file}">
          <cylinder length="${body_height}" radius="${body_width/2}"/>
        </xacro:unless>
      </geometry>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <cylinder length="${body_height}" radius="${body_width/2}"/>
      </geometry>
    </collision>
  </link>

  <gazebo reference="${namespace}/base_link">
    <material>Gazebo/${color}</material>
  </gazebo>

</robot>
