<?xml version="1.0"?>
<!--

Gazebo Shredder Definition File
Author: James Jackson

-->

<robot name="shredder" xmlns:xacro="http://ros.org/wiki/xacro">
<!-- Properties -->
<xacro:property name="namespace" value="shredder" />
<xacro:property name="use_mesh_file" value="true" />
<xacro:property name="mesh_file" value="package://magicc_sim/meshes/firefly.dae" />
<xacro:property name="mass" value="3.81" /> <!-- [kg] -->
<xacro:property name="body_width" value="0.505" /> <!-- [m] -->
<xacro:property name="body_height" value="0.1" /> <!-- [m] -->
<xacro:property name="rolling_moment_coefficient" value="0.000001" />
<xacro:property name="body_inertia">
  <inertia ixx="0.0347563" ixy="0.0" ixz="0.0" iyy="0.0458929" iyz="0.0" izz="0.0977" />
</xacro:property>


<!-- *********************** GAZEBO ROBOT DEFINITION ******************* -->
<link name="${namespace}/base_link">
  <inertial>
    <mass value="${mass}" />  <!-- [kg] -->
    <origin xyz="0 0 0" />
    <xacro:insert_block name="body_inertia" />
  </inertial>

  <visual>
    <origin xyz="0 0 0" rpy="0 0 1.571" />
    <geometry>
      <xacro:if value="${use_mesh_file}">
        <!-- <mesh filename="${mesh_file}" scale="0.001 0.001 0.001" /> -->
        <mesh filename="${mesh_file}" scale="1 1 1" />
      </xacro:if>
      <xacro:unless value="${use_mesh_file}">
        <cylinder length="${body_height}" radius="${body_width}"/>
      </xacro:unless>
    </geometry>
  </visual>

  <collision>
    <origin xyz="0 0 ${body_height/2.0}" rpy="0 0 0" />
    <geometry>
      <cylinder length="${0.1}" radius="${body_width}"/>
    </geometry>
  </collision>
</link>

  <gazebo reference="${namespace}/base_link">
    <material>Gazebo/$(arg color)</material>
  </gazebo>

  <!-- ************************* ROTOR DYNAMICS ********************** -->

  <!-- ROSflight_SIL -->
  <xacro:include filename="$(find magicc_sim_plugins)/xacro/ROSflight_SIL.xacro"/>
  <xacro:mikey_ROSflight_SIL namespace="${namespace}" parent_link="${namespace}/base_link"/>

  <!-- Simplified Dynamics -->
  <!-- <xacro:include filename="$(find magicc_sim_plugins)/xacro/multirotor_forces_and_moments.xacro"/> -->
  <!-- <xacro:shredder_forces_and_moments namespace="${namespace}" parent_link="${namespace}/base_link"/> -->


  <!-- ***************** SENSORS ******************* -->
  <!-- Ground Truth -->
  <xacro:include filename="$(find magicc_sim_plugins)/xacro/odometry_sensor.xacro"/>
  <xacro:ground_truth namespace="${namespace}" parent_link="${namespace}/base_link" />

  <!-- Mount an IMU -->
  <xacro:include filename="$(find magicc_sim_plugins)/xacro/imu.xacro"/>
  <xacro:perfect_IMU
    namespace="${namespace}"
    parent_link="${namespace}/base_link"
    imu_topic="imu"
    update_rate="500"/>

  <!--Enable Wind -->
  <!-- <xacro:include filename="$(find magicc_sim_plugins)/xacro/wind.xacro"/> -->
  <!-- <xacro:wind_param
    namespace="${namespace}"
    link_name="${namespace}/base_link"
    wind_pub_topic="wind"/> -->

  <!-- Mount an Altimeter -->
  <!-- <xacro:include filename="$(find magicc_sim_plugins)/xacro/altimeter.xacro"/>
  <xacro:perfect_baro
    namespace="${namespace}"
    parent_link="${namespace}/base_link"
    altimeter_topic="altimeter"/> -->

  <!-- Mount a Magnetometer -->
  <!-- Default Inclination and Declination for Provo, UT -->
  <!-- <xacro:include filename="$(find magicc_sim_plugins)/xacro/magnetometer.xacro"/>
  <xacro:hmc5883l
    namespace="${namespace}"
    parent_link="${namespace}/base_link"
    mag_topic="mag/data"
    inclination="1.14316156541"
    declination="0.198584539676"/> -->

  <!-- Mount an RGBD Camera -->
  <!-- <xacro:include filename="$(find magicc_sim_plugins)/xacro/rgbd.xacro"/>
  <xacro:xtion
    namespace="${namespace}"
    parent_link="${namespace}/bavese_link"/> -->

  <!-- Block Laser Scanner -->
  <!-- <xacro:include filename="$(find magicc_sim_plugins)/xacro/velodyne.xacro"/>
  <xacro:velodyne_custom
    namespace="${namespace}"
    parent_link="${namespace}/base_link"
    visualize="false">1
    <origin xyz="${body_width+0.1} 0 0" rpy="0 0 0"/>
  </xacro:velodyne_custom> -->

  <!-- Laser Scanner -->
  <!-- <xacro:include filename="$(find magicc_sim_plugins)/xacro/laser_scanner.xacro"/>
  <xacro:hokuyo_UTM-30LX
    namespace="${namespace}"
    parent_link="${namespace}/base_link"
    visualize="false"/> -->

  <!-- GPS -->
  <!-- <xacro:include filename="$(find magicc_sim_plugins)/xacro/GPS.xacro"/>
  <xacro:GPS_BYU
    namespace="${namespace}"
    parent_link="${namespace}/base_link"
    GPS_topic="gps"/> -->

  <!-- Camera -->
  <xacro:include filename="$(find magicc_sim_plugins)/xacro/camera.xacro"/>
  <xacro:simple_camera
    namespace="${namespace}"
    frame_rate="30"
    rgb_range="1000"
    parent_link="${namespace}/base_link"
    image_topic="rgb"
    image_camera_info_topic="camera_info">
    <origin xyz="${body_width+0.1} 0 0" rpy="0 0 0"/>
  </xacro:simple_camera>


</robot>
