<?xml version="1.0"?>

<robot name="junker" xmlns:xacro="http://ros.org/wiki/xacro">
  <!-- Properties -->
  <xacro:property name="namespace" value="$(arg mav_name)"/>
  <xacro:property name="wind_speed_topic" value="gazebo/wind_speed"/>
  <xacro:property name="command_topic" value="command"/>
  <xacro:property name="use_mesh_file" value="true" />
  <xacro:property name="mesh_file" value="package://magicc_sim/meshes/ju-87.dae"/>
  <xacro:property name="body_width" value="1.4"/>
  <xacro:property name="body_height" value="1.0" />
  <xacro:property name="body_length" value="1.6"/>
  <xacro:property name="mass" value="1.5"/>
  <xacro:property name="Jx" value="0.1147"/>
  <xacro:property name="Jy" value="0.0576"/>
  <xacro:property name="Jz" value="0.1712"/>
  <xacro:property name="Jxz" value="0.0015"/>

  <!-- Property Blocks -->
  <xacro:property name="empty_inertia">
    <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.001" />
  </xacro:property>

  <!-- Instantiate Link and Visual -->
  <link name="${namespace}/base_link">
    <inertial>
      <mass value="${mass}" />
      <origin xyz="0 0 0" />
      <inertia ixx="${Jx}" ixy="0.00" ixz="${Jxz}" iyy="${Jy}" iyz="0.00" izz="${Jz}" />
    </inertial>
    <visual name="plane_visual">
      <origin xyz="0 0 0" rpy="1.570796 0 1.570796" />
      <geometry>
        <xacro:if value="${use_mesh_file}">
          <mesh filename="${mesh_file}" scale="0.002 0.002 0.002" />
        </xacro:if>
        <xacro:unless value="${use_mesh_file}">
            <box size="${body_width} ${body_height} ${body_length}" />
        </xacro:unless>
      </geometry>
    </visual>
    <collision name="plane_collision">
      <origin xyz="0 0 0" rpy="1.570796 0 1.570796" />
      <geometry>
        <box size="${body_width} ${body_height} ${body_length}" />
      </geometry>
    </collision>

    <!-- Wheels -->
    <xacro:include filename="$(find magicc_sim_plugins)/xacro/wheel.xacro"/>
    <xacro:caster
      radius="0.05">
      <origin xyz="${body_length*0.31} -${body_width*0.25} -${body_height*0.45}"/>
    </xacro:caster>
    <xacro:caster
      radius="0.05">
      <origin xyz="${body_length*0.31} ${body_width*0.25} -${body_height*0.45}"/>
    </xacro:caster>
    <xacro:caster
      radius="0.02">
      <origin xyz="-${body_length*0.54} 0 -${body_height*0.15}"/>
    </xacro:caster>
  </link>

  <!-- Aerodynamics -->
  <xacro:include filename="$(find magicc_sim_plugins)/xacro/aircraft_forces_and_moments.xacro"/>
  <xacro:aerosonde
    namespace="${namespace}"
    parent_link="${namespace}/base_link"
    command_topic="command"/>

  <!-- Chase Camera -->
  <xacro:include filename="$(find magicc_sim_plugins)/xacro/camera.xacro"/>
  <xacro:simple_camera
    namespace="${namespace}/chase"
    frame_rate="30"
    rgb_range="1000"
    parent_link="${namespace}/base_link"
    image_topic="rgb"
    image_camera_info_topic="camera_info">
    <origin xyz="-${1.1*body_length} 0 ${0.8*body_height}"/>
  </xacro:simple_camera>

  <!-- Color -->
  <gazebo reference="${namespace}/base_link">
    <material>Gazebo/Blue</material>
  </gazebo>

  <!-- Sensors -->
  <xacro:include filename="$(find magicc_sim_plugins)/xacro/aircraft_truth.xacro"/>
  <xacro:aircraft_truth
    namespace="${namespace}"
    parent_link="${namespace}/base_link"
    wind_speed_topic="gazebo/wind_speed"/>

  <!-- Gimbal -->
  <xacro:include filename="$(find magicc_sim_plugins)/xacro/gimbal.xacro"/>
  <xacro:gimbal_ZENMUSE
    namespace="${namespace}"
    parent_link="${namespace}/base_link"
    camera_topic="rgb"
    frame_rate="30"
    pose_topic="${namespace}/gimbal/pose"
    command_topic="${namespace}/gimbal/control"
    use_slipring="true">
    <origin xyz="-${0.4*body_length} 0 -${0.4*body_height}" rpy="0 0 0"/>
  </xacro:gimbal_ZENMUSE>

  <!-- Airspeed -->
  <xacro:include filename="$(find magicc_sim_plugins)/xacro/airspeed.xacro"/>
  <xacro:airspeed_MPXV5004G
    namespace="${namespace}"
    parent_link="${namespace}/base_link"
    airspeed_topic="airspeed/data">
  </xacro:airspeed_MPXV5004G>

  <!-- GPS -->
  <xacro:include filename="$(find magicc_sim_plugins)/xacro/GPS.xacro"/>
  <xacro:GPS_BYU
    namespace="${namespace}"
    parent_link="${namespace}/base_link"
    GPS_topic="gps/data"
    update_rate="1">
  </xacro:GPS_BYU>

  <!-- Barometer -->
  <xacro:include filename="$(find magicc_sim_plugins)/xacro/barometer.xacro"/>
  <xacro:Barometer_MS5611
    namespace="${namespace}"
    parent_link="${namespace}/base_link"
    baro_topic="baro/data">
  </xacro:Barometer_MS5611>

  <!-- Sonar -->
  <xacro:include filename="$(find magicc_sim_plugins)/xacro/sonar.xacro"/>
  <xacro:Sonar_MB1030
    namespace="${namespace}"
    parent_link="${namespace}/base_link"
    sonar_topic="sonar/data">
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </xacro:Sonar_MB1030>

  <!-- IMU -->
  <xacro:include filename="$(find magicc_sim_plugins)/xacro/imu.xacro"/>
  <xacro:IMU_MPU6050
    namespace="${namespace}"
    parent_link="${namespace}/base_link"
    imu_topic="imu/data"
    update_rate="500">
  </xacro:IMU_MPU6050>

</robot>
